Fix typos
thepowersgang/rust_os pull request #9
Opened 2023-12-06 06:38 UTC by kianmeng

Found via `typos --hidden --format brief`

2023-12-06 13:10 UTC, thepowersgang requested changes
Blindly using a script is usually not a good idea, make sure to sanity check its output before committing.

2023-12-06 13:10 UTC, thepowersgang commented on Kernel/Core/lib/mem/boxed.rs
> +				// SAFE: Tell me again, why is allow unsafe?
`alloc`, not `allow` - Did you review this?

2023-12-06 13:10 UTC, thepowersgang commented on Kernel/Modules/block_cache/lib.rs
> +	/// Get the size for a block on the underlying volume
`of` not `for` - Bug report on the typo fixing tool :)

2023-12-06 13:10 UTC, thepowersgang commented on Kernel/Modules/input_ps2/pl050.rs
> +		// TODO: Unknown what this does, Access did it.
While strictly speaking this is a "correct" fix... `Acess` is the actual name of the project being referenced.

2023-12-06 13:10 UTC, thepowersgang commented on Kernel/rundir/arm_bootloader/fdt-realview-pb-a8.dts
> +			device_type = "allocated_rom";
Probably not a correct fix, as this is an external API

2023-12-06 13:10 UTC, thepowersgang commented on Notes/AsyncTake3.md
> +- Metaadata lookup (acceptable for that to be done in a worker or to be blocking)
"Metadata" - Bug report on your fixing tool

2023-12-06 13:10 UTC, thepowersgang commented on Notes/TODO.txt
> +- AccessNative-esque test suite?
See previous comments about "Acess" being the correct name

2023-12-06 13:10 UTC, thepowersgang commented on Notes/UserAPI-Networking.md
> + 2. Use the Access model of type+address
"Acess" again

2023-12-06 13:10 UTC, thepowersgang commented on Usermode/liballoc_system/lib.rs
> +//#![feature(option_builtin_traits)] // For !Send
This is a rust feature name, so it was correct originally.

2023-12-06 13:10 UTC, thepowersgang commented on Usermode/loader/bin/src/elf/mod.rs
> +	file: &'a mut R,	// File is pre-sought to the start of the PHENT list
"seeked" is correct in context, as it refers to the "seek" syscall

2023-12-07 23:16 UTC, thepowersgang approved these changes

2023-12-08 10:36 UTC, merged

2023-12-09 05:58 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: